name: Build from Branch

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Consistent project ID to use for caching'
        required: true
      branch:
        description: 'Branch to check project out'
        required: true
        default: 'develop'
      buildMethod:
        description: 'Build method to call in the repository'
        required: false
      buildTarget:
        description: 'Build target'
        required: false
        default: 'Android'
      buildMethodParameters:
        description: 'Parameters to pass to the build method'
        required: false


