name: Build from Branch

on:
  workflow_dispatch:
    inputs:
      projectId:
        description: 'Consistent project ID to use for caching'
        required: true
      branch:
        description: 'Branch to check project out'
        required: true
        default: 'develop'
      buildMethod:
        description: 'Build method to call in the repository'
        required: false
      buildTarget:
        description: 'Build target'
        required: false
        default: 'Android'
      buildMethodParameters:
        description: 'Parameters to pass to the build method'
        required: false

jobs:
  call_build_apk_workflow:
    runs-on:
      labels: Ubuntu-8-32-300
    
    steps:
    - name: Placeholder Step
      run: echo "This step is a placeholder"
      
    - name: Call Build APK Workflow
      uses: EmergentEntertainment/infinite-inside-vr/.github/workflows/build.yml@main
      with:
        projectId: ${{ inputs.projectId }}
        branch: ${{ inputs.branch }}
        buildMethod: ${{ inputs.buildMethod }}
        buildTarget: ${{ inputs.buildTarget }}
        buildMethodParameters: ${{ inputs.buildMethodParameters }}
      
    env:
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      GITHUB_PRIVATE_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
