name: Check Pull Request

on:
  pull_request:
    branches: [ master ]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  TOKEN: ${{ secrets.PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-GameCITest-Android
          restore-keys: |
            Library-build-
            Library-

      - name: Build Unity
        uses: game-ci/unity-builder@v2
        with:
          version: 2020.3.32f1
          targetPlatform: Android
          buildMethod: BuildScript.PerformScriptOnlyBuild

      - name: Check for errors
        if: ${{ failure() }}
        run: |
          echo "There are errors in the Build Unity job."
          echo "This pull request cannot be merged."
          # Add a comment to the pull request to notify the person who made the pull request that there are errors.
          curl -H "Authorization: Bearer ${{ env.TOKEN }}" \
               -X POST \
               -d '{"body": "There are errors in the build. This pull request cannot be merged ❌"}' \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/${{ github.event.pull_request.number }}/comments"
