name: Create and Email Unity Package

on: workflow_dispatch

jobs:
  package_and_send:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        find Assets/ -name \*.meta > metaList
        mkdir a
        cat metaList
        ls -la
        cd Assets/ && ls -la
    - uses: pCYSl5EDgo/create-unitypackage@v1.1.1
      with:
        package-path: 'a/output.unitypackage'
        include-files: metaList
      id: create_package

    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        path: a
        name: package
        
  send_email:
    needs: package_and_send
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package
          path: ${{ github.workspace }}/downloaded_package
      
      - run: ls ${{ github.workspace }}/
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
            server_address: smtp.gmail.com
            server_port: 465
            secure: true
            username: mazeTestEmail2000@gmail.com
            password: zeuclyjtgymlfqde
            subject: GitHub Actions Unity package
            to: erin.bateman@emergent-entertainment.com
            from: Shadow Build <mazeTestEmail2000@gmail.com>
            body: Shadow Branch Build job completed successfully!
            attachments: ${{ github.workspace }}/downloaded_package
