name: Generate Test Files

on:
  workflow_dispatch

jobs:
  generate-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create folders and files
        run: |
          mkdir -p Builds/Android
          echo "Dummy Android APK content" > Builds/Android/Android.apk
          echo "Dummy Android main obb content" > Builds/Android/Android.main.obb
          echo "This is the original content of Android.main.obb" > Builds/Android/Android.main.obb.original

      - name: Show generated files
        run: ls -R Builds 

      - name: Create Shadow folder, move and rename OBB file
        run: |
          mkdir -p Builds/Android/com.mazetheory.shadow
          mv Builds/Android/Android.main.obb Builds/Android/com.mazetheory.shadow/main.1.com.mazetheory.shadow.obb

      - name: Delete original OBB file
        run: rm Builds/Android/Android.main.obb.original

      - name: Rename and zip files
        run: |
          cd Builds
          zip -r Build.zip Android
          rm -r Android

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: Builds/Build.zip
