name: Upload Oculus Quest Build

#needs testing

on:
  workflow_dispatch

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Upload Oculus Quest Build
      run: |
        #may need to edit this to get correct path
        ovr-platform-util.exe 
      
    - name: Upload Oculus Quest Build
      run: |
        upload-quest-build --app_id 3732099523498937 \
        --app_secret 0efa19f4fb1ffbca0e650d7f3ec55229 \
        --apk "C:\Builds\oculus_quest.apk" \
        --obb "C:\Builds\oculus_quest.main.obb" \
        --assets-dir "C:\Builds\ExpansionFiles" \
        --asset-files-config "C:\Builds\addressable-expansion-files-config.json" \
        --channel "DAILY_BUILDS"
